### ISSUE TITLE
Installation Failed

### ISSUE THREAD

**Issue by Arne74** [Zendaug/Mplus-Tools#3]
I installed the add-on as suggested but can't see add-ons in Excel. I checked options in Excel. It says the add-on is active. I use Win7 and Excel2013. Any ideas how to solve the issue?

**Comment by Zendaug** [comment]
Once the add-in is loaded, try restarting Excel. Under the menu Add-Ins, you should be able to see a menu "Mplus Tools". In Visual Basic (under the "Developer" tab), you should be able to see all of the macros and associated forms.
